### ISSUE TITLE
tarihe gore siralama

### ISSUE THREAD

**Issue by mustafauysal** [codeui/chevent#9]
Etkinlik siralamasi yaparken, en yakin etkinlik en ustte olacak sekilde olursa daha guzel olur sanki.
<img width="373" alt="screen shot 2015-10-09 at 11 13 56" src="https://cloud.githubusercontent.com/assets/1421387/10388987/10be6e96-6e77-11e5-97a2-77c415c575d1.png">

**Comment by coderontheroad** [comment]
issue yanlış yere açılmış, bu repo sadece etkinlikleri eklemek için oluşturulmuş. Asıl repo chrome için şu adreste: https://github.com/codeui/chevent-chrome

**Comment by mustafauysal** [comment]
@coderontheroad digerini repoyu gormemisim. Sagolasin.
